apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-webpage
  namespace: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-webpage
  template:
    metadata:
      labels:
        app: basic-webpage
    spec:
      containers:
      - name: basic-webpage-container
        image: imshashannk/basic-website-using-html-css:latest
        ports:
        - containerPort: 80


'''
apiVersion: v1
kind: Service
metadata:
  name: basic-webpage-service
  namespace: cicd  # Ensure the namespace is created, or remove this line to use the default namespace
spec:
  selector:
    app: basic-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


