kind: Deployment
metadata:
  name: basic-webpage
  namespace: cicd  # Ensure the namespace is created, or remove this line to use the default namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-webpage
  template:
    metadata:
      labels:
        app: basic-webpage
    spec:
      containers:
      - name: basic-webpage
        image: imshashannk/basic-website-using-html-css:latest  # Replace with your actual Docker Hub username and image tag
        ports:
        - containerPort: 80

